version: '2'
services:

    prometheus:
        image: prom/prometheus:latest
        volumes:
            - /var/prometheus:/etc/prometheus
        ports:
            - "9090:9090"
        command:
            - "-config.file=/etc/prometheus/prometheus.yml"

    node-exporter:
        image: prom/node-exporter:latest
        ports:
          - '9111:9100'

    grafana:
        image: grafana/grafana:latest
        ports:
          - "3000:3000"
    
    cadvisor:
        image: google/cadvisor:latest
        ports:
            - "8080:8080"
        volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro
          
    uireact:
        image: experiencedevops/reactapp:e1daeea
        environment:
          BASE_URL: http://extelb.mytechexplorations.com:9090
        ports:
          - "80:80"
       
